# Working with JSON and SQL data

In [3]:
import pandas as pd

In [9]:
pd.read_json('test.json')

         id                                        ingredients
0     18009  [baking powder, eggs, all-purpose flour, raisi...
1     28583  [sugar, egg yolks, corn starch, cream of tarta...
2     41580  [sausage links, fennel bulb, fronds, olive oil...
3     29752  [meat cuts, file powder, smoked sausage, okra,...
4     35687  [ground black pepper, salt, sausage casings, l...
...     ...                                                ...
9939  30246  [large egg yolks, fresh lemon juice, sugar, bo...
9940  36028  [hot sauce, butter, sweet potatoes, adobo sauc...
9941  22339  [black pepper, salt, parmigiano reggiano chees...
9942  42525  [cheddar cheese, cayenne, paprika, plum tomato...
9943   1443  [cold water, olive oil, lime wedges, garlic cl...

[9944 rows x 2 columns]

## it also have same Features as CSV like chunks 
Link : https://pandas.pydata.org/docs/reference/api/pandas.read_json.html

### Fetching From Link

In [16]:
pd.read_json("https://api.exchangerate-api.com/v4/latest/INR")

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-19,1742342401,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-19,1742342401,0.0424
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-19,1742342401,0.8150
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-19,1742342401,1.0500
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-19,1742342401,4.5300
...,...,...,...,...,...,...,...
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-19,1742342401,1.2600
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-19,1742342401,2.8500
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-19,1742342401,0.2090
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-19,1742342401,0.3320
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-19,1742342401,0.3080

# Working with SQL

In [19]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 18.1 MB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py) ... done
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp312-cp312-macosx_11_0_arm64.whl size=247957 sha256=9feab7a41837bd256daf6aad0bb71fec4f8a34c71c9b9c87ee031fd0c4490343
  Stored in directory: /Users/narendrasingh/Library/Caches/pip/wheels/03/17/fa/d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [21]:
import mysql.connector

In [ ]:
conn = mysql.connector.connect(host='localhost',user='root',password='Enter the Passworld',database='world')

In [ ]:
pd.read_